
--
-- Postgres SQL Schema dump automatic generated by geni
--


-- TABLES 

CREATE TABLE schema_migrations (
 id character varying (255) NOT NULL
);

CREATE TABLE users (
 email character varying  NOT NULL,
 id integer  NOT NULL,
 created_at timestamp without time zone  NOT NULL,
 updated_at timestamp without time zone  NOT NULL
);

-- CONSTRAINTS 

ALTER TABLE schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (id);

ALTER TABLE users ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- INDEXES 

CREATE UNIQUE INDEX schema_migrations_pkey ON public.schema_migrations USING btree (id)

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email)

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id)

-- SEQUENCES 

CREATE SEQUENCE users_id_seq AS integer START WITH 1 MINVALUE 1 MAXVALUE 2147483647 INCREMENT BY 1 CYCLE;

